#name-template: 'PyPop $NEXT_PATCH_VERSION'
name-template: 'PyPop $RESOLVED_VERSION'
#tag-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease: false
#prerelease-identifier: 'rc'
#include-pre-releases: true
version-template: '$COMPLETE'
commitish: 'main'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'installation'
  - title: 'Internal'
    labels:
      - 'github_actions'
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
category-template: '### $TITLE'      
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Install via PyPI
  ```
  pip install -U pypop-genomics
  ```
  <!-- START cut-and-paste to NEWS.md -->

  ## $RESOLVED_VERSION - YYYY-MM-DD
  
  $CHANGES

  [$RESOLVED_VERSION]: https://github.com/$OWNER/$REPOSITORY/releases/tag/v$RESOLVED_VERSION

  <!-- END cut-and-paste to NEWS.md -->

  A full history of changes is available in [`NEWS.md`](https://github.com/$OWNER/$REPOSITORY/blob/main/NEWS.md).

  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
