name-template: 'PyPop $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
#prerelease: true
include-pre-releases: true
#prerelease-identifier: 'rc'
#version-template: '$COMPLETE'
commitish: 'main'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'installation'
  - title: 'Internal'
    labels:
      - 'github_actions'
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
category-template: '### $TITLE'      
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Install via PyPI
  ```
  pip install -U pypop-genomics
  ```

  <!-- START cut-and-paste to NEWS.md -->

  ## $NEXT_PATCH_VERSION - YYYY-MM-DD
  
  $CHANGES

  [$NEXT_PATCH_VERSION]: https://github.com/alexlancaster/pypop/releases/tag/v$NEXT_PATCH_VERSION

  <!-- END cut-and-paste to NEWS.md -->

  A full history of changes is available in [`NEWS.md`](https://github.com/alexlancaster/pypop/blob/main/NEWS.md).

  **Full Changelog:** https://github.com/alexlancaster/pypop/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
