repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: ^tests/base\.py$
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.5"
    hooks:
      - id: ruff
        args: ["--show-fixes"] # FIXME: add "--exit-zero" to list to commit to ignore ruff fixes
      - id: ruff-format
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.21  # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # for checking C extension code
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        args: ['--style=LLVM', '--verbose']
        types_or: [c]
        # exclude where code is mostly from upstream source
        exclude: '^src/(pval|haplo-stats)/.*'

#  - repo: https://github.com/ItsZcx/pre-commit-hooks
#    rev: v1.4.0
#    hooks:
#     - id: cppcheck
#       files: \.(c|h)$
#       args: ['--enable=style,warning,portability,performance,missingInclude']

# FIXME: enable for debugging hooks
#  - repo: meta
#    hooks:
#    - id: identity
#      exclude: '^src/(pval|haplo-stats)/.*'

exclude: 'tests/data/.*|data/.*|website/reference/.*|src/obsolete/.*|website/html_root/.*'

ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
