# FIXME: these live outside pyproject.toml for the moment because
# setuptools >=75 which supports them is not available on Python <=3.7.
# once we drop support for older Pythons we can merge back into
# pyproject.toml

[[tool.setuptools.ext-modules]]
name = "PyPop._EWSlatkinExact"
sources = ["src/slatkin-exact/monte-carlo_wrap.i", "src/slatkin-exact/monte-carlo.c"]
swig-opts = ["-Isrc/SWIG", "-Isrc"]

[[tool.setuptools.ext-modules]]
name = "PyPop._Emhaplofreq"
sources = ["src/emhaplofreq/emhaplofreq_wrap.i", "src/emhaplofreq/emhaplofreq.c"]
swig-opts = ["-Isrc/SWIG", "-Isrc"]
include-dirs = ["src/emhaplofreq"]
extra-compile-args = ["-D__SWIG__=1",
                      "-DDEBUG=0",
                      "-DEXTERNAL_MODE=1",
                      "-DXML_OUTPUT=1"]
depends = ["src/SWIG/typemap.i",
          "src/emhaplofreq/emhaplofreq.h",
          "src/emhaplofreq/drand48.c"]

[[tool.setuptools.ext-modules]]
name = "PyPop._Gthwe"
sources = [
        "src/gthwe/gthwe_wrap.i",
        "src/gthwe/hwe.c",
        "src/gthwe/cal_const.c",
        "src/gthwe/cal_n.c",
        "src/gthwe/cal_prob.c",
        "src/gthwe/check_file.c",
        "src/gthwe/do_switch.c",
        "src/gthwe/new_rand.c",
        "src/gthwe/ln_p_value.c",
        "src/gthwe/to_calculate_log.c",
        "src/gthwe/print_data.c",
        "src/gthwe/random_choose.c",
        "src/gthwe/read_data.c",
        "src/gthwe/select_index.c",
        "src/gthwe/stamp_time.c",
        "src/gthwe/test_switch.c",
        "src/gthwe/statistics.c"]
swig-opts = ["-Isrc/SWIG", "-Isrc"]
include-dirs = ["src/gthwe"]
library-dirs = []
libraries=["gsl", "gslcblas"]
extra-compile-args=["-D__SWIG__=1",
    "-DDEBUG=0",
    "-DXML_OUTPUT=1",
    "-DSUPPRESS_ALLELE_TABLE=1",
    "-DINDIVID_GENOTYPES=1",
]
depends = ["src/SWIG/typemap.i", "src/gthwe/func.h", "src/gthwe/hwe.h"]
