[tool.cibuildwheel]
skip = ["*-win32", "*_i686", "*-musllinux_*"]  # skip 32-bit builds and musllinux
test-extras = ["test"]
test-command = "pytest -s -v {package}/tests"

[tool.cibuildwheel.linux]
before-all="yum install -y swig gsl-devel"

#[tool.cibuildwheel.macos]
#before-all = "brew install swig gsl"
# FIXME: on MacOS, cibuildwheel team suggests building these from
# source within the container, rather than using 'brew'
