name: Feature request
description: Suggest an idea for this project
title: "[Feature request]: Please replace this with a concise description of your request"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a feature request for future consideration!  Please visit the  [feature request](https://github.com/alexlancaster/pypop/blob/main/CONTRIBUTING.rst#feature-requests-and-feedback) in our contributors guide for background on good feature requests.

  - type: textarea
    id: feature-request-issue
    attributes:
      label: A clear description of your feature request
      description: A clear and concise description of the feature request. Please make sure you include a concrete use-case of a specific problem that the feature would address.
      placeholder: |
        I'm always frustrated when I do X [...] 
    validations:
      required: true
  - type: textarea
    id: feature-request-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Be specific.
      placeholder: |
        When X happens, I think we should also add X
    validations:
      required: true
  - type: textarea
    id: feature-request-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
