<?xml version='1.0'?>
<!DOCTYPE xsl:stylesheet PUBLIC "-//Thomson Lab//DTD Unofficial XSL//EN"  
                         "xsl.dtd">  
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format"
                version='1.0'>

 <xsl:import href="http://db2latex.sourceforge.net/docbook.xsl"/>

 <xsl:variable name="latex.article.preamblestart">
<xsl:text>% --------------------------------------------        &#10;</xsl:text>
<xsl:text>% Autogenerated LaTeX file for articles                       &#10;</xsl:text>
<xsl:text>% --------------------------------------------        &#10;</xsl:text>
<xsl:text>\ifx\pdfoutput\undefined&#10;</xsl:text>
<xsl:text>\documentclass[spanish,french,english,letter,10pt,twoside]{article}       &#10;</xsl:text>
<xsl:text>\else&#10;</xsl:text>
<xsl:text>\documentclass[pdftex, spanish,french,english,letter,10pt,twoside]{article}       &#10;</xsl:text>
<xsl:text>\fi&#10;</xsl:text>
 </xsl:variable>

 <xsl:template match="ulink">
  <xsl:text>{\tt </xsl:text>
  <xsl:value-of select="@url"/> 
  <xsl:text>}</xsl:text>
 </xsl:template>
 
</xsl:stylesheet>

<!--
Local variables:
sgml-local-catalogs: ("catalog")
End:
-->
