"""Generate API stubs."""

from pathlib import Path


def generate_deprecated_stubs(build_lib, deprecated_modules):
    """Create stub modules in build/lib to keep old CamelCase imports working."""
    for old_name, new_name in deprecated_modules.items():
        parts = old_name.split(".")
        stub_file = Path(build_lib, *parts).with_suffix(".py")
        stub_file.parent.mkdir(parents=True, exist_ok=True)
        with open(stub_file, "w") as f:
            f.write(f"""\
# THIS FILE IS AUTOMATICALLY GENERATED
import warnings
from .{new_name.split(".")[-1]} import *

#warnings.warn(
#    "Module '{old_name}' is deprecated; use '{new_name}' instead",
#    DeprecationWarning,
#    stacklevel=2
#)
""")
