name: Build PyPop

on:
  workflow_dispatch:  
  release: 
     types: 
      - published

jobs:
  publish_zenodo:
    name: Publish to zenodo on production releases only
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && '!github.event.release.prerelease'
    steps:
       - name: Checkout the contents of your repository
         uses: actions/checkout@v4
       - run: |
           cp .zenodo.json .zenodo.orig.json
           echo "{\"version\": \"1.0.0a40\"}" | cat .zenodo.orig.json - | jq -s add > .zenodo.json
           rm .zenodo.orig.json
       - name: Create a draft snapshot of your repository contents as a new
               version in collection 8383807 on Zenodo using metadata
               from repository file .zenodo.json
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
         uses: zenodraft/action@0.10.0
         with:
           collection: 8383807
           metadata: .zenodo.json
           publish: false
           sandbox: false
           compression: tar.gz
           upsert-doi: true
           upsert-location: doi
           verbose: true
