name: Build PyPop

on:
  workflow_dispatch:  
  release: 
     types: 
      - published

jobs:
  publish_zenodo:
    name: Publish to zenodo on production releases only
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && '!github.event.release.prerelease'
    steps:
       - name: Checkout the contents of your repository
         uses: actions/checkout@v4
       - name: Upsert the version in the metadata in .zenodo.json
         run: |
           cp .zenodo.json .zenodo.orig.json
           echo "{\"version\": \"$GITHUB_REF_NAME\"}" | cat .zenodo.orig.json - | jq -s add > .zenodo.json
           rm .zenodo.orig.json
       - name: Upsert the version in the metadata in CITATION.cff
         run: |
           yq -i ".version = \"$GITHUB_REF_NAME\"" CITATION.cff
       - name: Push changes back to repo files
         run: |
           git config --global user.name ci
           git config --global user.email "username@users.noreply.github.com"
           git add .zenodo.json CITATION.cff
           git commit -m "Upserted version into CITATION.cff and into .zenodo.json"
           git push
       - name: Create a draft snapshot of your repository contents as a new
               version in collection 8383807 on Zenodo using metadata
               from repository file .zenodo.json
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
         uses: zenodraft/action@0.10.0
         with:
           collection: 8383807
           metadata: .zenodo.json
           publish: false
           sandbox: false
           compression: tar.gz
           upsert-doi: true
           upsert-location: doi
           verbose: true
