name: Build PyPop

on:
  workflow_dispatch:  
  release: 
     types: 
      - published

jobs:
  publish_zenodo:
    name: Publish to zenodo on production releases only
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && '!github.event.release.prerelease'
    steps:
       - name: Checkout the contents of your repository
         uses: actions/checkout@v4
       - name: Upsert the version in the metadata in .zenodo.json
         run: |
           cp .zenodo.json .zenodo.orig.json
           echo "{\"version\": \"$GITHUB_REF_NAME\"}" | cat .zenodo.orig.json - | jq -s add > .zenodo.json
           rm .zenodo.orig.json
       - name: Upsert the version in the metadata in CITATION.cff
         run: |
           yq -i ".version = \"$GITHUB_REF_NAME\"" CITATION.cff
       - name: Push changes back to repo files
         run: |
           git config --global user.name ci
           git config --global user.email "username@users.noreply.github.com"
           git add .zenodo.json CITATION.cff
           git commit -m "Upserted version into CITATION.cff and into .zenodo.json"
           git push origin $GITHUB_REF_NAME
       - name: Create a draft snapshot of your repository contents as a new
               version in collection 1234567 on Zenodo Sandbox using metadata
               from repository file .zenodo.json
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
         uses: zenodraft/action@0.10.0
         with:
           collection: 1243488
           metadata: .zenodo.json
           publish: false
           sandbox: true
           compression: tar.gz
           upsert-doi: true
           upsert-location: doi
           verbose: true
      # steps:
      #   # This step is not needed at the moment but might decide to add on more steps in the future
      #   - name: Set up Node.js
      #     uses: actions/setup-node@v3
      #     with:
      #       node-version: 16
      #   - name: Upload to Zenodo
      #     id: release
      #     uses: alexlancaster/upload-to-zenodo@main
      #     with:
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
      #       zenodo_token: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
      #       zenodo_deposition_id: 1243453
      #       zenodo_publish: true
      #       zenodo_sandbox: true
      #       commit_message: 'chore: update ${file_name} for Zenodo release'
      #       update_metadata_files: true
      #       codemeta_json: false
      #       citation_cff: true
      #       zenodo_json: true

      #   # Get the doi from the `release` step
      #   - name: Get the output doi
      #     run: echo "The released doi was ${{ steps.release.outputs.doi }}"
