name: pypop.org website and docs generation
on:
  push:
    paths:
      - 'README.rst'
      - 'website/**'
      - 'src/PyPop/CommandLineInterface.py'
      - '!website/README.md'
      - '!reference/**'
      - '.github/workflows/documentation.yaml'
  pull_request:
    paths:
      - 'README.rst'
      - 'website/**'
      - 'src/PyPop/CommandLineInterface.py'
      - '!website/README.md'
      - '!reference/**'
      - '.github/workflows/documentation.yaml'
  workflow_dispatch:
    paths:
      - 'README.rst'
      - 'website/**'
      - 'src/PyPop/CommandLineInterface.py'
      - '!website/README.md'
      - '!reference/**'
      - '.github/workflows/documentation.yaml'
  release: 
     types: 
      - published

      
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check GitHub Action permissions
        run: |
          echo "github.actor:  ${{ toJson(github.actor) }}"
          echo "github.triggering_actor:  ${{ toJson(github.triggering_actor) }}"
          echo "github.repository_owner:  ${{ toJson(github.repository_owner) }}"
          echo "github.repository_owner:  ${{ toJson(github.repository_owner) }}"
          echo "github.repository: ${{ toJson(github.repository) }}"
          echo "github.event.pull_request.base.repo.full_name: ${{ toJson(github.event.pull_request.base.repo.full_name) }}"
          echo "github.event.pull_request.head.repo.full_name: ${{ toJson(github.event.pull_request.head.repo.full_name) }}"
          echo "github context: ${{ toJson(github) }}"
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install setuptools_scm sphinx piccolo-theme sphinx_rtd_theme myst_parser rst2pdf sphinx_togglebutton sphinx-argparse
          sudo apt clean
          sudo apt-get update
          sudo apt-get install --fix-missing -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-luatex texlive-xetex
      - name: Sphinx build
        run: |
          # latex build in separate directory
          # it generates a lot of files we don't need to keep
          sphinx-build -b latex website _latexbuild
          make -C _latexbuild
          # create _build directory and move the PDF there
          mkdir _build
          cp _latexbuild/*.pdf _build/
          # now build the HTML
          sphinx-build website _build

      - name: Deploy to beta site
        uses: peaceiris/actions-gh-pages@v3
        # only update beta site if base and head branches match, not for forks
        # forks cannot access secrets to deploy, see: https://github.com/orgs/community/discussions/26829
        if: ${{ (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name) }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: alexlancaster/beta.pypop.org
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: _build/
          force_orphan: true
          
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        # only update on either a push, or published release on the main branch
        if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
