name: Update citations upon CITATION.cff changes

on:
  push:
    paths:
      - CITATION.cff
      - '.github/workflows/run_citations.yml'
      - '.github/workflows/update_citations.yml'      

jobs:
  update-citations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # use customized version of cffconvert
          pip install git+https://github.com/alexlancaster/cffconvert.git@combine_features#egg=cffconvert

      - name: Trigger citation update workflow
        uses: ./.github/workflows/update_citations.yml  # reference the reusable workflow
        with:
          CITATION_DIR: 'src/PyPop/citation'
          INIT_FILE: 'src/PyPop/__init__.py'

